### ISSUE TITLE
How to subscribe to zed-ros-interfaces topic Object?

### ISSUE THREAD

**Issue by Momofaiz** [stereolabs/zed-ros-interfaces#12]
Hi, i want to subscribe to the topic Object. So i started by running the zed_obj_det_sub node but nothing happens!
And when i runthe command "rostopic list", the topic Object doesn't exist.

**Comment by Myzhar** [comment]
Hi @Momofaiz 
please refer to the [online documentation](https://www.stereolabs.com/docs/ros/object-detection).
