### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by ricber** [stereolabs/zed-ros-interfaces#4]
Can you please explain how to read data from the ZED2 camera without a GPU by using this package? Is there a launch file or a node to launch?

**Comment by Myzhar** [comment]
You cannot use this package to read data without a GPU.
This is a package that defines the ZED custom messages for object detection and custom services to control the ZED node.
You must run a [ZED Node](https://github.com/stereolabs/zed-ros-wrapper) on a machine with GPU to retrieve data

**Comment by ricber** [comment]
Thank you for your answer! But could you please explain what does it mean the following phrase written on this package’s README file: “ Note: this package does not require CUDA, hence it can be used to receive the ZED data also on machines not equipped with an Nvidia GPU”.
