### ISSUE TITLE
MATLAB rosgenmsg() Issue with zed_interfaces

### ISSUE THREAD

**Issue by jaronski** [stereolabs/zed-ros-interfaces#5]
when trying to get zed_interfaces custom messages into Matlab (Windows) i ran into the following error:
`Error using logical
NaN values cannot be converted to logicals.

Error in ros.internal.MessageParser/getDataStructure (line 399)
                                    feval(obj.MLTypeConverter(dataType),str2double(constantValues{i}));

Error in ros.internal.ServiceParser/getContentsOfServiceDefinition (line 161)
            serviceDefinition = getDataStructure(parser,filePath,...

Error in ros.internal.ServiceParser/getServiceDefinitionHelper (line 123)
                getContentsOfServiceDefinition(obj,parser,filePath,contentsOfFileForRequest,CirDependList);

Error in ros.internal.ServiceParser/getServiceDefinition (line 80)
                getServiceDefinitionHelper(obj,CirDependList);

Error in ros.internal.clientserverEmitter (line 43)
    [msgDefnForRequest, msgDefnForResponse] = getServiceDefinition(parser);

Error in rosgenmsg (line 348)
            [genFiles, requestDependencies, responseDependencies] = ros.internal.clientserverEmitter(...`

After debugging in Matlab i found out that the srv start_remote_stream.srv is causing the trouble. When removing this srv file from the ros_custom_msgs folder and commenting out in the CMakeLists.txt i was able to rosgenmsg the zed_interface and have all the custom msgs and srvs in matlab EXCEPT start_remote_stream.srv. 

Ahh also if you have trouble with rosgenmsg and MATLAB 2021b check this [link:](https://de.mathworks.com/matlabcentral/answers/1462699-rosgenmsg-can-find-cmake-in-r2021a-but-not-in-r2021b?s_tid=prof_contriblnk) 

and look for the temporary workaround ... [this is important](https://de.mathworks.com/matlabcentral/answers/1462699-rosgenmsg-can-find-cmake-in-r2021a-but-not-in-r2021b#comment_1760354)

Maybe this helps someone

**Comment by Myzhar** [comment]
Hi @jaronski 
thank you for sharing this useful information for all the Matlab users.
